source 'https://rubygems.org'

gem 'aws'
gem 'rake'
gem 'nanoc', '~> 4.0.0rc1'
gem 'rdiscount'
gem 'httpclient'
gem 'builder'
gem 'image_size'
gem 'mime-types'
gem 'nokogiri'
gem 'htmlentities'
gem 'systemu'
gem 'coderay'
gem 'rouge'
gem 'adsf'
gem 'haml'
gem "link-checker"
gem 'simpleidn'
gem 'guard-nanoc'
gem 'cssminify'
gem 'uglifier'
gem 'w3c_validators'
