source 'https://rubygems.org'

gem 'nanoc', '~> 4.0.0'
gem 'guard-nanoc', '~> 2.0.0'
gem 'rdiscount'
gem 'httpclient'
gem 'builder'
gem 'image_size'
gem 'mime-types'
gem 'nokogiri'
gem 'htmlentities'
gem 'systemu'
gem 'rouge'
gem 'adsf'
gem 'haml'
gem 'cssminify'
gem 'uglifier'
gem 'w3c_validators'
