source 'https://rubygems.org'

gem 'aws'
gem 'rake'
gem 'nanoc', '~> 4.0.0b4'
gem 'rdiscount'
gem 'httpclient'
gem 'builder'
gem 'image_size'
gem 'mime-types'
gem 'nokogiri'
gem 'htmlentities'
gem 'systemu'
gem 'coderay'
gem 'adsf'
gem 'haml'
gem 'simpleidn'
gem 'guard-nanoc'
