include Nanoc::Helpers::Rendering
include Nanoc::Helpers::LinkTo
include Nanoc::Helpers::Blogging
include Nanoc::Helpers::Text
include Nanoc::Helpers::XMLSitemap
include TagsCategoriesHelper
include MoreHelper
include FingerprintHelper
include TextHelper
include TagCloudHelper
